from main import pygame
image_menu_screen = pygame.image.load('data/screen_images/menu_screen.png')
image_game_screen = pygame.image.load('data/screen_images/game_screen.png')
image_after_game_screen = pygame.image.load('data/screen_images/screen_after_game.png')
image_score_screen = pygame.image.load('data/screen_images/score_screen.png')
image_about_screen = pygame.image.load('data/screen_images/screen_about.png')
image_tutorial_screen = pygame.image.load('data/screen_images/tutorial_screen.png')
image_yellow_minion = pygame.image.load('data/balls/yellow.png')
image_unicorn = pygame.image.load('data/balls/unicorn.png')
image_banana = pygame.image.load('data/balls/banana.png')
image_purple_minion = pygame.image.load('data/balls/purple.png')
image_green_minion = pygame.image.load('data/balls/green.png')
image_red_minion = pygame.image.load('data/balls/red.png')
image_symbol = pygame.image.load('data/balls/black.png')
image_button_start_white = pygame.image.load('data/buttons/start_white.png')
image_button_quit_white = pygame.image.load('data/buttons/quit_white.png')
image_button_quit_2_white = pygame.image.load('data/buttons/quit2_white.png')
image_button_level_easy_white = pygame.image.load('data/buttons/level_easy_white.png')
image_button_level_easy_black = pygame.image.load('data/buttons/level_easy_black.png')
image_button_level_normal_white = pygame.image.load('data/buttons/level_normal_white.png')
image_button_level_normal_black = pygame.image.load('data/buttons/level_normal_black.png')
image_button_level_hard_white = pygame.image.load('data/buttons/level_hard_white.png')
image_button_level_hard_black = pygame.image.load('data/buttons/level_hard_black.png')
image_button_sounds_on_white = pygame.image.load('data/buttons/sounds_on_white.png')
image_button_sounds_on_black = pygame.image.load('data/buttons/sounds_on_black.png')
image_button_sounds_off_white = pygame.image.load('data/buttons/sounds_off_white.png')
image_button_sounds_off_black = pygame.image.load('data/buttons/sounds_off_black.png')
image_button_menu_white = pygame.image.load('data/buttons/menu_white.png')
image_button_score_white = pygame.image.load('data/buttons/score_white.png')
image_button_about_white = pygame.image.load('data/buttons/about_white.png')
image_button_reset_white = pygame.image.load('data/buttons/reset_white.png')
image_button_time_white = pygame.image.load('data/buttons/time_white.png')
image_arrows = pygame.image.load('data/buttons/arrows.png')
#
image_choose_game_mode_screen = pygame.image.load('data/new_data/new_screens/choose_game_mode_screen.png')
image_choose_settings_screen = pygame.image.load('data/new_data/new_screens/choose_settings_screen.png')
image_first_screen = pygame.image.load('data/new_data/new_screens/first_screen.png')
image_new_score_screen = pygame.image.load('data/new_data/new_screens/score_screen.png')

image_button_play_white = pygame.image.load('data/new_data/new_buttons/button_play_white_white.png')
image_button_new_menu_white = pygame.image.load('data/new_data/new_buttons/button_menu_white.png')
image_button_new_score_white = pygame.image.load('data/new_data/new_buttons/button_score_white.png')
image_button_new_reset_white = pygame.image.load('data/new_data/new_buttons/button_reset_white.png')
image_button_new_quit_white = pygame.image.load('data/new_data/new_buttons/button_quit_white.png')

image_button_modern_white = pygame.image.load('data/new_data/new_buttons/button_modern_white.png')
image_button_classic_white = pygame.image.load('data/new_data/new_buttons/button_classic_white.png')
image_button_dodge_white = pygame.image.load('data/new_data/new_buttons/button_dodge_white.png')
image_modern_info = pygame.image.load('data/new_data/new_buttons/big_info.png')
image_classic_info = pygame.image.load('data/new_data/new_buttons/classic_info.png')
image_dodge_info = pygame.image.load('data/new_data/new_buttons/dodge_info.png')

image_agnes_white = pygame.image.load('data/new_data/objects/agnes_white.png')
image_margo_white = pygame.image.load('data/new_data/objects/margo_white.png')
image_judith_white = pygame.image.load('data/new_data/objects/judith_white.png')
image_agnes_obj = pygame.image.load('data/new_data/objects/agnes.png')
image_margo_obj = pygame.image.load('data/new_data/objects/margo.png')
image_judith_obj = pygame.image.load('data/new_data/objects/judith.png')

image_choosing_arrow = pygame.image.load('data/new_data/new_buttons/arrow.png')
image_button_30s = pygame.image.load('data/new_data/new_buttons/30_white.png')
image_button_45s = pygame.image.load('data/new_data/new_buttons/45_white.png')
image_button_60s = pygame.image.load('data/new_data/new_buttons/60_white.png')
image_button_hard_white = pygame.image.load('data/new_data/new_buttons/hard_white.png')
image_button_normal_white = pygame.image.load('data/new_data/new_buttons/normal_white.png')
image_button_easy_white = pygame.image.load('data/new_data/new_buttons/easy_white.png')
